package car;

import static java.lang.System.exit;

/**
 *
 * @author brett
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    Car c = new Car();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBox1 = new javax.swing.JCheckBox();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        SeatType = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CupHolder = new javax.swing.JCheckBox();
        Radio = new javax.swing.JCheckBox();
        Tire = new javax.swing.JCheckBox();
        Oil = new javax.swing.JCheckBox();
        Tank = new javax.swing.JCheckBox();
        Tow = new javax.swing.JCheckBox();
        Roof = new javax.swing.JCheckBox();
        ModelC = new javax.swing.JCheckBox();
        ModelE = new javax.swing.JCheckBox();
        ModelCS = new javax.swing.JCheckBox();
        V8Engine = new javax.swing.JCheckBox();
        V12Engine = new javax.swing.JCheckBox();
        PumaSeats = new javax.swing.JCheckBox();
        SealSeats = new javax.swing.JCheckBox();
        KomodoSeats = new javax.swing.JCheckBox();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBox1.setText("jCheckBox1");

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Done");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Model");

        jLabel2.setText("Engine");

        jButton2.setText("Quit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        SeatType.setText("Seat Type");

        jLabel3.setText("Extras");

        CupHolder.setText("32oz Cup Holders, $1");
        CupHolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CupHolderActionPerformed(evt);
            }
        });

        Radio.setText("Blaupunkt New York 800 Radio, $900");
        Radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioActionPerformed(evt);
            }
        });

        Tire.setText("Spare Tire, $400");
        Tire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TireActionPerformed(evt);
            }
        });

        Oil.setText("Free First Oil Change, $75");
        Oil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OilActionPerformed(evt);
            }
        });

        Tank.setText("Oversized Gas Tank, $900");
        Tank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TankActionPerformed(evt);
            }
        });

        Tow.setText("Towing Package, $3000");
        Tow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TowActionPerformed(evt);
            }
        });

        Roof.setText("Sun Roof, C $1900, E $2200, CS $3000");
        Roof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoofActionPerformed(evt);
            }
        });

        ModelC.setText("C $28,000");
        ModelC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModelCActionPerformed(evt);
            }
        });

        ModelE.setText("E $41,000");
        ModelE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModelEActionPerformed(evt);
            }
        });

        ModelCS.setText("CS $54,000");
        ModelCS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModelCSActionPerformed(evt);
            }
        });

        V8Engine.setText("V-8 Engine (C only)");
        V8Engine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V8EngineActionPerformed(evt);
            }
        });

        V12Engine.setText("V-12 Engine, (E and CS only)");
        V12Engine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V12EngineActionPerformed(evt);
            }
        });

        PumaSeats.setText("Puma Skin Seats, $7000 (E only)");
        PumaSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PumaSeatsActionPerformed(evt);
            }
        });

        SealSeats.setText("Seal Skin Seats, $5600 (C only)");
        SealSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SealSeatsActionPerformed(evt);
            }
        });

        KomodoSeats.setText("Komodo Dragon Skin Seats, $12,000 (CS only, with rice and sauce)");
        KomodoSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KomodoSeatsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(ModelE)
                    .addComponent(ModelCS)
                    .addComponent(ModelC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(259, 259, 259)
                        .addComponent(SeatType))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(V12Engine)
                            .addComponent(V8Engine))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SealSeats, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PumaSeats, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(KomodoSeats, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(201, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(CupHolder)
                    .addComponent(Radio)
                    .addComponent(Tire)
                    .addComponent(Oil)
                    .addComponent(Tank)
                    .addComponent(Tow)
                    .addComponent(Roof))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(SeatType))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ModelC)
                            .addComponent(V12Engine))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(ModelE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(V8Engine)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ModelCS))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(KomodoSeats)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PumaSeats)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SealSeats)))
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(CupHolder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Radio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tire)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Oil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tank)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Roof)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        c.done();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        c.quit();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void RadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioActionPerformed

        if (Radio.isSelected()){

            c.addRadio();
        }
        else{
            c.removeRadio();
        }
    }//GEN-LAST:event_RadioActionPerformed

    private void CupHolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CupHolderActionPerformed

        
        if (CupHolder.isSelected()){

            c.addCupHolder();
        }
        else{

            c.removeCupHolder();
        }
        
    }//GEN-LAST:event_CupHolderActionPerformed

    private void TankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TankActionPerformed

        if (Tank.isSelected()){

            c.addTank();
        }
        else{

            c.removeTank();
        }
    }//GEN-LAST:event_TankActionPerformed

    private void TireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TireActionPerformed

        if (Tire.isSelected()){

            c.addTire();
        }
        else{

            c.removeTire();
        }
    }//GEN-LAST:event_TireActionPerformed

    private void OilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OilActionPerformed

        if (Oil.isSelected()){

            c.addOil();
        }
        else{

            c.removeOil();
        }
    }//GEN-LAST:event_OilActionPerformed

    private void TowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TowActionPerformed

        if (Tow.isSelected()){

            c.addTow();
        }
        else{

            c.removeTow();
        }
    }//GEN-LAST:event_TowActionPerformed

    private void RoofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoofActionPerformed

        if (Roof.isSelected()){

            c.addRoof();
        }
        else{

            c.removeRoof();
        }
    }//GEN-LAST:event_RoofActionPerformed

    private void ModelCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModelCActionPerformed

        if (ModelC.isSelected()){

            c.addModelC();
        }
        else{

            c.removeModelC();
        }
    }//GEN-LAST:event_ModelCActionPerformed

    private void ModelEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModelEActionPerformed

        if (ModelE.isSelected()){
 
            c.addModelE();
        }
        else{

            c.removeModelE();
        }
    }//GEN-LAST:event_ModelEActionPerformed

    private void ModelCSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModelCSActionPerformed

        if (ModelCS.isSelected()){

            c.addModelCS();
        }
        else{

            c.removeModelCS();
        }
    }//GEN-LAST:event_ModelCSActionPerformed

    private void PumaSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PumaSeatsActionPerformed

        if (PumaSeats.isSelected()){

            c.addSeatsPuma();
        }
        else{

            c.removeSeatsPuma();
        }
    }//GEN-LAST:event_PumaSeatsActionPerformed

    private void SealSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SealSeatsActionPerformed

        if (SealSeats.isSelected()){

            c.addSeatsSeal();
        }
        else{

            c.removeSeatsSeal();
        }
    }//GEN-LAST:event_SealSeatsActionPerformed

    private void KomodoSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KomodoSeatsActionPerformed

        if (KomodoSeats.isSelected()){

            c.addSeatsKomodo();
        }
        else{

            c.removeSeatsKomodo();
        }
    }//GEN-LAST:event_KomodoSeatsActionPerformed

    private void V8EngineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V8EngineActionPerformed

        if (V8Engine.isSelected()){
            c.addV8Engine();
        } 
        else{

            c.removeV8Engine();
        }
    }//GEN-LAST:event_V8EngineActionPerformed

    private void V12EngineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V12EngineActionPerformed

        if (V12Engine.isSelected()){

            c.addV12Engine();
        }
        else{

            c.removeV12Engine();
        }
    }//GEN-LAST:event_V12EngineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CupHolder;
    private javax.swing.JCheckBox KomodoSeats;
    private javax.swing.JCheckBox ModelC;
    private javax.swing.JCheckBox ModelCS;
    private javax.swing.JCheckBox ModelE;
    private javax.swing.JCheckBox Oil;
    private javax.swing.JCheckBox PumaSeats;
    private javax.swing.JCheckBox Radio;
    private javax.swing.JCheckBox Roof;
    private javax.swing.JCheckBox SealSeats;
    private javax.swing.JLabel SeatType;
    private javax.swing.JCheckBox Tank;
    private javax.swing.JCheckBox Tire;
    private javax.swing.JCheckBox Tow;
    private javax.swing.JCheckBox V12Engine;
    private javax.swing.JCheckBox V8Engine;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    // End of variables declaration//GEN-END:variables
}
